FROM ubuntu:18.10
RUN apt update -y
RUN apt install -y curl python3-pip git pkg-config libx11-dev libx11-xcb-dev libxcb1-dev libxcb-icccm4-dev
RUN pip3 install --user wheezy.template
RUN curl -O https://raw.githubusercontent.com/usnistgov/hevx/master/test/CTestScript.cmake

