FROM ubuntu:18.04
RUN apt update -y
RUN apt install -y curl python3 python3-pip git pkg-config libx11-dev libx11-xcb-dev libxcb1-dev libxcb-icccm4-dev
RUN pip3 install --user wheezy.template
RUN mkdir cmake && curl -L "https://github.com/Kitware/CMake/releases/download/v3.11.4/cmake-3.11.4-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C cmake

RUN curl -O https://raw.githubusercontent.com/usnistgov/hevx/master/test/CTestScript.cmake

