FROM fedora:28

ARG VULKAN_VER=1.1.101.0
ARG BUILD_VULKAN_URL=https://raw.githubusercontent.com/usnistgov/hevx/update-docker/test/build-vulkan-sdk.py

ARG CMAKE_VER=3.12.4
ARG CMAKE_URL=https://github.com/Kitware/CMake/releases/download/v$CMAKE_VER/cmake-$CMAKE_VER-Linux-x86_64.tar.gz

RUN dnf update -y
RUN dnf install -y python git cmake gcc-c++ make boost-\* openssl-devel \
  glm-devel libpng-devel wayland-devel libpciaccess-devel libX11-devel \
  libXpresent libxcb xcb-util libxcb-devel libXrandr-devel xcb-util-wm-devel \
  xcb-util-keysyms-devel
RUN pip3 install --user wheezy.template
RUN mkdir cmake && curl -L $CMAKE_URL | tar --strip-components=1 -xz -C cmake

RUN mkdir -p vulkan/src
WORKDIR vulkan/src
RUN curl -O $BUILD_VULKAN_URL
RUN python3 build-vulkan-sdk.py -G "Unix Makefiles" --cmake cmake \
  --install_dir /vulkan $VULKAN_VER

WORKDIR ../..
ENV VULKAN_SDK=/vulkan
