FROM ubuntu:18.04
RUN apt update -y
RUN apt install -y curl python3-pip cmake git pkg-config libx11-dev libx11-xcb-dev \
    libxcb1-dev libxkb-common-dev libxcb-icccm4-dev libwayland-dev libxrandr-dev libxcb-randr0-dev
RUN pip3 install --user wheezy.template
RUN mkdir cmake && curl -L "https://github.com/Kitware/CMake/releases/download/v3.12.4/cmake-3.12.4-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C cmake

RUN mkdir -p vulkan/src
WORKDIR vulkan/src
RUN curl -O https://raw.githubusercontent.com/usnistgov/hevx/update-docker/test/build-vulkan-sdk.py
RUN python3 build-vulkan-sdk.py -G "Unix Makefiles" --install_dir /vulkan 1.1.101.0
