FROM centos:7.6.1810
RUN yum update -y
RUN yum install -y centos-release-scl epel-release
RUN yum install -y devtoolset-8\* python34 git cmake3 boost-\* glm-devel libpng-devel wayland-devel \
	libpciaccess-devel libX11-devel libXpresent libxcb xcb-util libxcb-devel libXrandr-devel \
	xcb-util-wm-devel xcb-util-keysyms-devel
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py
RUN pip3 install --user wheezy.template

RUN mkdir -p vulkan/src
WORKDIR vulkan/src
RUN curl -O https://raw.githubusercontent.com/usnistgov/hevx/update-docker/test/build-vulkan-sdk.py
RUN scl enable devtoolset-8 -- python3 build-vulkan-sdk.py -G "Unix Makefiles" --install_dir /vulkan 1.1.101.0

WORKDIR ../..
ENV VULKAN_SDK=/vulkan
