FROM ubuntu:16.04
ARG CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.11.4/cmake-3.11.4-Linux-x86_64.tar.gz"
RUN apt update -y
RUN apt install -y software-properties-common python-software-properties
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt update -y
RUN apt install -y curl python3-pip g++-7 git pkg-config libx11-dev libx11-xcb-dev libxcb1-dev libxcb-icccm4-dev
RUN update-alternatives \
  --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
  --slave /usr/bin/g++ g++ /usr/bin/g++-7 \
  --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 \
  --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 \
  --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
RUN update-alternatives \
  --install /usr/bin/python python /usr/bin/python3 60
RUN pip3 install --user wheezy.template
RUN mkdir cmake && curl -L $CMAKE_URL | tar --strip-components=1 -xz -C cmake

