language: cpp

dist: xenial

services:
  - docker

env:
  global:
    - CONFIGURATION_TYPE=RelWithDebInfo
    - SOURCE_DIR=/s
    - BUILD_DIR=/b
    - DOCKER_IMAGE=wesleygriffin/hevx
    - DOCKER_ARGS=-v $TRAVIS_BUILD_DIR:$SOURCE_DIR -w $BUILD_DIR
    - ROOT=-DCTEST_DASHBOARD_ROOT=$BUILD_DIR
    - TYPE=-DCTEST_CONFIGURATION_TYPE=$CONFIGURATION_TYPE
    - CTEST_ARGS=-VV $ROOT $TYPE -S $SOURCE_DIR/test/CTestScript.cmake

matrix:
  include:
    - name: "CentOS 7 (GCC 8.2.1)"
      env: PLATFORM=el7 CTEST_CMD="scl enable devtoolset-8 -- ctest3"
    - name: "Fedora 28 (GCC 8.2.1)"
      env: PLATFORM=f28 CTEST_CMD="/cmake/bin/ctest"
    - name: "Fedora 29 (GCC 8.2.1)"
      env: PLATFORM=f29 CTEST_CMD="ctest"
    - name: "Unbuntu 18.10 (GCC 8.2.0)"
      env: PLATFORM=cosmic CTEST_CMD="ctest"

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
  - docker pull $DOCKER_IMAGE:$PLATFORM

script:
  - docker run $DOCKER_ARGS $DOCKER_IMAGE:$PLATFORM $CTEST_CMD $CTEST_ARGS
