language: cpp

dist: xenial

services:
  - docker

env:
  global:
    - DOCKER_ARGS="-v $TRAVIS_BUILD_DIR:/s -w /b"
    - CONFIG_TYPE="-DCTEST_CONFIGURATION_TYPE=RelWithDebInfo"
    - CTEST_ARGS="-VV $CONFIG_TYPE -S /s/test/CTestScript.cmake"

matrix:
  include:
    - name: "CentOS 7 (GCC 8.2.1)"
      env: PLATFORM=el7 CTEST_CMD="scl enable devtoolset-8 -- ctest3"
    - name: "Fedora 28 (GCC 8.2.1)"
      env: PLATFORM=f28 CTEST_CMD="/cmake/bin/ctest"
    - name: "Fedora 29 (GCC 8.2.1)"
      env: PLATFORM=f29 CTEST_CMD="ctest"
    - name: "Unbuntu 18.04 (GCC 7.3.0)"
      env: PLATFORM=bionic CTEST_CMD="/cmake/bin/ctest"
    - name: "Unbuntu 18.10 (GCC 8.2.0)"
      env: PLATFORM=cosmic CTEST_CMD="ctest"

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
  - docker pull wesleygriffin/hevx:$PLATFORM

script:
  - docker run $DOCKER_ARGS wesleygriffin/hevx:$PLATFORM $CTEST_CMD $CTEST_ARGS
